name: Import OpenAPI to Apidog
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codes
        uses: actions/checkout@v3
      - name: import
        if: contains(github.event.head_commit.message, '[OpenAPI]')
        run: |
          # Import swagger.json to apidog
          curl -X "POST" \
            "https://api.apidog.com/v1/projects/${{ secrets.API_PROJECT }}/import-openapi?locale=ja-JP" \
            -H 'X-Apidog-Api-Version: 2024-03-28' \
            -H 'Authorization: Bearer ${{ secrets.API_TOKEN }}' \
            -H 'Content-Type: application/json; charset=utf-8' \
            -d $'{"input":{"url": "https://raw.githubusercontent.com/alphauslabs/blueapidocs/master/openapiv3/apidocs.json"}}'